site_name: LiveHD and Pyrope

repo_url: https://github.com/masc-ucsc/livehd
  # edit_url: https://github.com/masc-ucsc/docs/edit/main/docs

remote_branch: gh-pages

plugins:
  - search

theme:
  name: material
  font:
    code: Fira Code
  logo: assets/pyrope5.png
  features:
    - search.suggest
    - navigation.sections
    - navigation.instant
    - navigation.indexes
      # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - stylesheets/table.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

