name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - run: pip install mkdocs-pymdownx-material-extras mkdocs-redirects mkdocs-minify-plugin mkdocs-mermaid2-plugin

      - run: mkdocs build

      - run: find ./site -name "*.html" -exec sed -i -E 's#<a href="https:\/\/github.com\/masc-ucsc\/livehd\/edit\/master\/(.*)"#<a href="https://github.com/masc-ucsc/docs/edit/main/\1"#g' {} +

      - run: ghp-import --no-jekyll --push --force --no-history --branch=gh-pages ./site
